### ISSUE TITLE
History should report on init

### ISSUE THREAD

**Issue by ghost** [MonetDBSolutions/mroll#2]
The history table should be populated with the initial event to initialize the migration table.

**Comment by sstalin** [comment]
There is no history tbl. The history command reads the migrations tbl.

**Comment by ghost** [comment]
That's meant. The migration table should be initialized the moment it is created.

**Comment by sstalin** [comment]
the migration tbl holds only migrations records in current design. I'm not sure why init record is needed or wher to put it

**Comment by ghost** [comment]
ok. let's close this one.
