### ISSUE TITLE
Viewing revision patches (and their result)

### ISSUE THREAD

**Issue by ghost** [MonetDBSolutions/mroll#5]
The history gives only the revision ideas. Using a -p should also show their content, and result applied to the database (errors?)

mroll history
<Revision id=fe00de6bfa19 description=Initialize the database>
mroll history -p
-- identifiers used by mroll
-- id=fe00de6bfa19
-- description=create tbl foo
-- ts=2020-05-08T14:19:46.839773
-- migration:upgrade
	create table foo (a string, b string);
	alter table foo add constraint foo_pk primary key (a);
-- migration:downgrade
	drop table foo;

**Comment by sstalin** [comment]
ok this could be useful command line option

**Comment by sstalin** [comment]
addressed in v0.3.0
