### ISSUE TITLE
Downgrade --preview 

### ISSUE THREAD

**Issue by ghost** [MonetDBSolutions/mroll#6]
Downgrading in a lineage tree would walk all the way back to a specifically named revision-id.
With a --preview  option to see what will happen if you apply it.

**Comment by sstalin** [comment]
what would be preview option the downgrade sql?
Currently I have 
`mroll rollback -n 2` to rollback 2 steps 
`mroll rollback` , just  one(latest)

**Comment by ghost** [comment]
People are bad counters.
- where is the documentation for this
- identifying the point you wanna return too is easier.

**Comment by sstalin** [comment]
addressed in v0.3.0
