### ISSUE TITLE
Report revision-id on errors

### ISSUE THREAD

**Issue by ghost** [MonetDBSolutions/mroll#8]
If mroll encounters a failing revision upgrade, then report its id. Otherwise it is hard to find what revision was wrong.
(PycharmProjects) bash-3.2$ mroll upgrade
3F000!CREATE SCHEMA: name ‘notary’ already in use
…    raise exception(msg)
pymonetdb.exceptions.OperationalError: SELECT: no such table ‘mroll_revisions’ (edited) 
9:33
Be more defensive. This sequence requires a better error message, not a stack trace.

**Comment by sstalin** [comment]
should be addressed in v0.3.0
